// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQyQ2mcoEe6a70yDA3e9_eKMfmbvCRNKY',
    appId: '1:44353113298:web:dc7bee0501c258c1cff10b',
    messagingSenderId: '44353113298',
    projectId: 'lumina-study-8c64c',
    authDomain: 'lumina-study-8c64c.firebaseapp.com',
    storageBucket: 'lumina-study-8c64c.firebasestorage.app',
    measurementId: 'G-J4TCVJ0WG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_Af5shtpWNibacJ3pZqRDGUMvTN5n8Y',
    appId: '1:44353113298:android:cb55526a41e6c1dbcff10b',
    messagingSenderId: '44353113298',
    projectId: 'lumina-study-8c64c',
    storageBucket: 'lumina-study-8c64c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByY7vblH6vV5mqlg5zZ52p8MUfOAZYF7s',
    appId: '1:44353113298:ios:e98cee8b6aba0061cff10b',
    messagingSenderId: '44353113298',
    projectId: 'lumina-study-8c64c',
    storageBucket: 'lumina-study-8c64c.firebasestorage.app',
    iosClientId: '44353113298-h1ttgslr088ppf7698ud253u2jgbephd.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminaStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByY7vblH6vV5mqlg5zZ52p8MUfOAZYF7s',
    appId: '1:44353113298:ios:e98cee8b6aba0061cff10b',
    messagingSenderId: '44353113298',
    projectId: 'lumina-study-8c64c',
    storageBucket: 'lumina-study-8c64c.firebasestorage.app',
    iosClientId: '44353113298-h1ttgslr088ppf7698ud253u2jgbephd.apps.googleusercontent.com',
    iosBundleId: 'com.example.luminaStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQyQ2mcoEe6a70yDA3e9_eKMfmbvCRNKY',
    appId: '1:44353113298:web:9182ea96873b7320cff10b',
    messagingSenderId: '44353113298',
    projectId: 'lumina-study-8c64c',
    authDomain: 'lumina-study-8c64c.firebaseapp.com',
    storageBucket: 'lumina-study-8c64c.firebasestorage.app',
    measurementId: 'G-DMFT4N2N4S',
  );

}